---
playbook_debug: yes
# region
azure_resource_group: "{{ lookup('env','AZURE_RESOURCE_GROUP') | default('ocp', true) }}"
azure_region: "{{ lookup('env','AZURE_REGION') | default('westus', true) }}"
# vm
azure_nic_name: "{{ lookup('env','AZURE_NIC_NAME') | default('testnic001', true) }}"
azure_virtual_network: "{{ lookup('env','AZURE_VIRTUAL_NETWORK') | default('ocp-vpc', true) }}"
azure_subnet: "{{ lookup('env','AZURE_SUBNET') | default('default', true) }}"
azure_security_group: "{{ lookup('env','AZURE_SECURITY_GROUP') | default('node', true) }}"
azure_ip_allocation_method: "{{ lookup('env','AZURE_IP_ALLOCATION_METHOD') | default('Dynamic', true) }}"
azure_vm_name: "{{ lookup('env','AZURE_VM_NAME') | default('testvm001', true) }}"
azure_vm_size: "{{ lookup('env','AZURE_VM_SIZE') | default('Standard_DS1_v2', true) }}"
azure_storage_account: "{{ lookup('env','AZURE_STORAGE_ACCOUNT') | default('ocpdisks', true) }}"
azure_storage_container: "{{ lookup('env','AZURE_STORAGE_CONTAINER') | default('vhds', true) }}"
azure_vm_username: "{{ lookup('env','AZURE_VM_USERNAME') | default('azure-user', true) }}"
azure_vm_password: "{{ lookup('env','AZURE_VM_PASSWORD') | default('changeme1!', true) }}"
azure_vm_ssh_public_key: "{{ lookup('env','AZURE_VM_SSH_PUBLIC_KEY') | default('', true) }}"
# auth
client_id: "{{ lookup('env','AZURE_CLIENT_ID') | default('', true) }}"
secret: "{{ lookup('env', 'AZURE_SECRET') | default('', true) }}"
subscription_id: "{{ lookup('env','AZURE_SUBSCRIPTION_ID') | default('', true) }}"
tenant: "{{ lookup('env','AZURE_TENANT') | default('', true) }}"
# images
azure_vm_image: "{{ lookup('env','AZURE_VM_IMAGE') | default('CentOS_7.4', true) }}"
azure_vm_images: 
  - {name: 'CentOS_7.4', offer: 'rhel-byol', publisher: 'RedHat', sku: 'rhel74', version: '7.4.0'}
  - {name: 'RHEL_7.4', offer: 'CentOS', publisher: 'OpenLogic', sku: '7.4', version: 'latest'}
